baseURL = "https://cezarcruz.com.br"
languageCode = "pt-BR"
title = "Blog do Cezar"
theme = "hugo-theme-minos"
canonifyURLs = true

[params]
    googleAnalytics = "UA-37762884-1"
    enableDisqus = true

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "author"